// Code generated by protogenall. DO NOT EDIT.
// source: chat.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// ChatClient is the client API for the Chat service.
type ChatClient interface {
	Send(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Ack, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error)
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, UploadSummary], error)
	Converse(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) Send(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/chat.v1.Chat/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error) {
	stream, err := c.cc.NewStream(ctx, &Chat_ServiceDesc.Streams[0], "/chat.v1.Chat/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Message]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

func (c *chatClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, UploadSummary], error) {
	stream, err := c.cc.NewStream(ctx, &Chat_ServiceDesc.Streams[1], "/chat.v1.Chat/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Chunk, UploadSummary]{ClientStream: stream}
	return x, nil
}

func (c *chatClient) Converse(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error) {
	stream, err := c.cc.NewStream(ctx, &Chat_ServiceDesc.Streams[2], "/chat.v1.Chat/Converse", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Message]{ClientStream: stream}
	return x, nil
}

// ChatServer is the server API for the Chat service.
type ChatServer interface {
	Send(context.Context, *Message) (*Ack, error)
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Message]) error
	Upload(grpc.ClientStreamingServer[Chunk, UploadSummary]) error
	Converse(grpc.BidiStreamingServer[Message, Message]) error
	mustEmbedUnimplementedChatServer()
}

// UnimplementedChatServer must be embedded to have forward compatible implementations.
type UnimplementedChatServer struct{}

func (UnimplementedChatServer) Send(context.Context, *Message) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedChatServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Message]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedChatServer) Upload(grpc.ClientStreamingServer[Chunk, UploadSummary]) error {
	return status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedChatServer) Converse(grpc.BidiStreamingServer[Message, Message]) error {
	return status.Error(codes.Unimplemented, "method Converse not implemented")
}
func (UnimplementedChatServer) mustEmbedUnimplementedChatServer() {}

func RegisterChatServer(s grpc.ServiceRegistrar, srv ChatServer) {
	s.RegisterService(&Chat_ServiceDesc, srv)
}

func _Chat_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/chat.v1.Chat/Send"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Send(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Message]{ServerStream: stream})
}

func _Chat_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).Upload(&grpc.GenericServerStream[Chunk, UploadSummary]{ServerStream: stream})
}

func _Chat_Converse_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).Converse(&grpc.GenericServerStream[Message, Message]{ServerStream: stream})
}

// Chat_ServiceDesc is the grpc.ServiceDesc for the Chat service.
var Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.v1.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Chat_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Chat_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Upload",
			Handler:       _Chat_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Converse",
			Handler:       _Chat_Converse_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chat.proto",
}
