// protogen.authz declares per-method access requirements (roles/permissions)
// as proto options. They are enforced at runtime by the interceptors in
// github.com/dvislobokov/protogen/authz — the annotation alone does nothing.
//
// Usage:
//
//   import "protogen/authz/authz.proto";
//
//   service Orders {
//     // Service-wide default for methods without their own annotation.
//     option (protogen.authz.default_requires) = { public: true };
//
//     rpc Cancel(CancelRequest) returns (CancelReply) {
//       option (protogen.authz.requires) = {
//         roles: { any_of: ["admin", "support"] }
//         permissions: { all_of: ["orders.write"] }
//       };
//     }
//   }

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.0.0
// source: protogen/authz/authz.proto

package authz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Rule matches a subject's attribute list (roles or permissions).
// Every set field must pass; an empty rule always passes.
type Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The subject must have at least one of these values ("oneOf").
	AnyOf []string `protobuf:"bytes,1,rep,name=any_of,json=anyOf,proto3" json:"any_of,omitempty"`
	// The subject must have every one of these values ("all").
	AllOf []string `protobuf:"bytes,2,rep,name=all_of,json=allOf,proto3" json:"all_of,omitempty"`
	// The subject must have none of these values.
	NoneOf        []string `protobuf:"bytes,3,rep,name=none_of,json=noneOf,proto3" json:"none_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_protogen_authz_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_protogen_authz_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_protogen_authz_authz_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetAnyOf() []string {
	if x != nil {
		return x.AnyOf
	}
	return nil
}

func (x *Rule) GetAllOf() []string {
	if x != nil {
		return x.AllOf
	}
	return nil
}

func (x *Rule) GetNoneOf() []string {
	if x != nil {
		return x.NoneOf
	}
	return nil
}

// Requirements declares who may call a method.
//
// An empty Requirements ({}) means "any authenticated subject". A method
// without any annotation (and no service default) is not checked at all.
type Requirements struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Roles the calling subject must satisfy.
	Roles *Rule `protobuf:"bytes,1,opt,name=roles,proto3" json:"roles,omitempty"`
	// Permissions the calling subject must satisfy.
	Permissions *Rule `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`
	// Public methods skip authentication and all checks.
	Public        bool `protobuf:"varint,3,opt,name=public,proto3" json:"public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Requirements) Reset() {
	*x = Requirements{}
	mi := &file_protogen_authz_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requirements) ProtoMessage() {}

func (x *Requirements) ProtoReflect() protoreflect.Message {
	mi := &file_protogen_authz_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requirements.ProtoReflect.Descriptor instead.
func (*Requirements) Descriptor() ([]byte, []int) {
	return file_protogen_authz_authz_proto_rawDescGZIP(), []int{1}
}

func (x *Requirements) GetRoles() *Rule {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Requirements) GetPermissions() *Rule {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Requirements) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

var file_protogen_authz_authz_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Requirements)(nil),
		Field:         58000,
		Name:          "protogen.authz.requires",
		Tag:           "bytes,58000,opt,name=requires",
		Filename:      "protogen/authz/authz.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Requirements)(nil),
		Field:         58000,
		Name:          "protogen.authz.default_requires",
		Tag:           "bytes,58000,opt,name=default_requires",
		Filename:      "protogen/authz/authz.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// Access requirements for this method.
	//
	// optional protogen.authz.Requirements requires = 58000;
	E_Requires = &file_protogen_authz_authz_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// Default requirements for every method of the service that does not carry
	// its own (protogen.authz.requires) option.
	//
	// optional protogen.authz.Requirements default_requires = 58000;
	E_DefaultRequires = &file_protogen_authz_authz_proto_extTypes[1]
)

var File_protogen_authz_authz_proto protoreflect.FileDescriptor

const file_protogen_authz_authz_proto_rawDesc = "" +
	"\n" +
	"\x1aprotogen/authz/authz.proto\x12\x0eprotogen.authz\x1a google/protobuf/descriptor.proto\"M\n" +
	"\x04Rule\x12\x15\n" +
	"\x06any_of\x18\x01 \x03(\tR\x05anyOf\x12\x15\n" +
	"\x06all_of\x18\x02 \x03(\tR\x05allOf\x12\x17\n" +
	"\anone_of\x18\x03 \x03(\tR\x06noneOf\"\x8a\x01\n" +
	"\fRequirements\x12*\n" +
	"\x05roles\x18\x01 \x01(\v2\x14.protogen.authz.RuleR\x05roles\x126\n" +
	"\vpermissions\x18\x02 \x01(\v2\x14.protogen.authz.RuleR\vpermissions\x12\x16\n" +
	"\x06public\x18\x03 \x01(\bR\x06public:Z\n" +
	"\brequires\x12\x1e.google.protobuf.MethodOptions\x18\x90\xc5\x03 \x01(\v2\x1c.protogen.authz.RequirementsR\brequires:j\n" +
	"\x10default_requires\x12\x1f.google.protobuf.ServiceOptions\x18\x90\xc5\x03 \x01(\v2\x1c.protogen.authz.RequirementsR\x0fdefaultRequiresB-Z+github.com/dvislobokov/protogen/authz;authzb\x06proto3"

var (
	file_protogen_authz_authz_proto_rawDescOnce sync.Once
	file_protogen_authz_authz_proto_rawDescData []byte
)

func file_protogen_authz_authz_proto_rawDescGZIP() []byte {
	file_protogen_authz_authz_proto_rawDescOnce.Do(func() {
		file_protogen_authz_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protogen_authz_authz_proto_rawDesc), len(file_protogen_authz_authz_proto_rawDesc)))
	})
	return file_protogen_authz_authz_proto_rawDescData
}

var file_protogen_authz_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protogen_authz_authz_proto_goTypes = []any{
	(*Rule)(nil),                        // 0: protogen.authz.Rule
	(*Requirements)(nil),                // 1: protogen.authz.Requirements
	(*descriptorpb.MethodOptions)(nil),  // 2: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 3: google.protobuf.ServiceOptions
}
var file_protogen_authz_authz_proto_depIdxs = []int32{
	0, // 0: protogen.authz.Requirements.roles:type_name -> protogen.authz.Rule
	0, // 1: protogen.authz.Requirements.permissions:type_name -> protogen.authz.Rule
	2, // 2: protogen.authz.requires:extendee -> google.protobuf.MethodOptions
	3, // 3: protogen.authz.default_requires:extendee -> google.protobuf.ServiceOptions
	1, // 4: protogen.authz.requires:type_name -> protogen.authz.Requirements
	1, // 5: protogen.authz.default_requires:type_name -> protogen.authz.Requirements
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	4, // [4:6] is the sub-list for extension type_name
	2, // [2:4] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protogen_authz_authz_proto_init() }
func file_protogen_authz_authz_proto_init() {
	if File_protogen_authz_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protogen_authz_authz_proto_rawDesc), len(file_protogen_authz_authz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_protogen_authz_authz_proto_goTypes,
		DependencyIndexes: file_protogen_authz_authz_proto_depIdxs,
		MessageInfos:      file_protogen_authz_authz_proto_msgTypes,
		ExtensionInfos:    file_protogen_authz_authz_proto_extTypes,
	}.Build()
	File_protogen_authz_authz_proto = out.File
	file_protogen_authz_authz_proto_goTypes = nil
	file_protogen_authz_authz_proto_depIdxs = nil
}
