// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.0.0
// source: checkout.proto

// No option go_package here either — managed mode fills it in.

package shop

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency int32

const (
	Currency_CURRENCY_UNSPECIFIED Currency = 0
	Currency_USD                  Currency = 1
	Currency_EUR                  Currency = 2
	Currency_GBP                  Currency = 3
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "CURRENCY_UNSPECIFIED",
		1: "USD",
		2: "EUR",
		3: "GBP",
	}
	Currency_value = map[string]int32{
		"CURRENCY_UNSPECIFIED": 0,
		"USD":                  1,
		"EUR":                  2,
		"GBP":                  3,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_checkout_proto_enumTypes[0].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_checkout_proto_enumTypes[0]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{0}
}

type ShippingSpeed int32

const (
	ShippingSpeed_SHIPPING_SPEED_UNSPECIFIED ShippingSpeed = 0
	ShippingSpeed_STANDARD                   ShippingSpeed = 1
	ShippingSpeed_EXPRESS                    ShippingSpeed = 2
)

// Enum value maps for ShippingSpeed.
var (
	ShippingSpeed_name = map[int32]string{
		0: "SHIPPING_SPEED_UNSPECIFIED",
		1: "STANDARD",
		2: "EXPRESS",
	}
	ShippingSpeed_value = map[string]int32{
		"SHIPPING_SPEED_UNSPECIFIED": 0,
		"STANDARD":                   1,
		"EXPRESS":                    2,
	}
)

func (x ShippingSpeed) Enum() *ShippingSpeed {
	p := new(ShippingSpeed)
	*p = x
	return p
}

func (x ShippingSpeed) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShippingSpeed) Descriptor() protoreflect.EnumDescriptor {
	return file_checkout_proto_enumTypes[1].Descriptor()
}

func (ShippingSpeed) Type() protoreflect.EnumType {
	return &file_checkout_proto_enumTypes[1]
}

func (x ShippingSpeed) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShippingSpeed.Descriptor instead.
func (ShippingSpeed) EnumDescriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{1}
}

type PlaceOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// required + email format
	CustomerEmail string `protobuf:"bytes,1,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
	// length bounds
	CustomerName string `protobuf:"bytes,2,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	// uuid format
	IdempotencyKey string `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// regex pattern
	PromoNote string `protobuf:"bytes,4,opt,name=promo_note,json=promoNote,proto3" json:"promo_note,omitempty"`
	// enum: must be a defined value and not the zero/unspecified one
	Currency Currency `protobuf:"varint,5,opt,name=currency,proto3,enum=shop.v1.Currency" json:"currency,omitempty"`
	// repeated with collection bounds; at least one item
	Items []*LineItem `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	// numeric range
	DiscountPercent int32 `protobuf:"varint,7,opt,name=discount_percent,json=discountPercent,proto3" json:"discount_percent,omitempty"`
	// proto3 optional — present-or-absent, and NOT required
	CouponCode *string `protobuf:"bytes,8,opt,name=coupon_code,json=couponCode,proto3,oneof" json:"coupon_code,omitempty"`
	// enum, defined values only
	ShippingSpeed ShippingSpeed `protobuf:"varint,9,opt,name=shipping_speed,json=shippingSpeed,proto3,enum=shop.v1.ShippingSpeed" json:"shipping_speed,omitempty"`
	// nested message, required
	ShippingAddress *Address `protobuf:"bytes,10,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	// must be true to proceed
	AcceptTerms bool `protobuf:"varint,11,opt,name=accept_terms,json=acceptTerms,proto3" json:"accept_terms,omitempty"`
	// free-form optional timestamp (no constraint) — shows a well-known message field
	RequestedDelivery *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=requested_delivery,json=requestedDelivery,proto3" json:"requested_delivery,omitempty"`
	// field_behavior: write-only + required (never echoed back; must be supplied)
	PaymentToken  string `protobuf:"bytes,13,opt,name=payment_token,json=paymentToken,proto3" json:"payment_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_checkout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderRequest) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

func (x *PlaceOrderRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *PlaceOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PlaceOrderRequest) GetPromoNote() string {
	if x != nil {
		return x.PromoNote
	}
	return ""
}

func (x *PlaceOrderRequest) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetItems() []*LineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PlaceOrderRequest) GetDiscountPercent() int32 {
	if x != nil {
		return x.DiscountPercent
	}
	return 0
}

func (x *PlaceOrderRequest) GetCouponCode() string {
	if x != nil && x.CouponCode != nil {
		return *x.CouponCode
	}
	return ""
}

func (x *PlaceOrderRequest) GetShippingSpeed() ShippingSpeed {
	if x != nil {
		return x.ShippingSpeed
	}
	return ShippingSpeed_SHIPPING_SPEED_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetShippingAddress() *Address {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *PlaceOrderRequest) GetAcceptTerms() bool {
	if x != nil {
		return x.AcceptTerms
	}
	return false
}

func (x *PlaceOrderRequest) GetRequestedDelivery() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedDelivery
	}
	return nil
}

func (x *PlaceOrderRequest) GetPaymentToken() string {
	if x != nil {
		return x.PaymentToken
	}
	return ""
}

type LineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineItem) Reset() {
	*x = LineItem{}
	mi := &file_checkout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineItem) ProtoMessage() {}

func (x *LineItem) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineItem.ProtoReflect.Descriptor instead.
func (*LineItem) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{1}
}

func (x *LineItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *LineItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *LineItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line1         string                 `protobuf:"bytes,1,opt,name=line1,proto3" json:"line1,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"` // ISO-3166 alpha-2
	PostalCode    string                 `protobuf:"bytes,4,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_checkout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type PlaceOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// field_behavior: server-assigned, read-only in the API surface
	OrderId       string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Currency      Currency `protobuf:"varint,2,opt,name=currency,proto3,enum=shop.v1.Currency" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_checkout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{3}
}

func (x *PlaceOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PlaceOrderResponse) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

var File_checkout_proto protoreflect.FileDescriptor

const file_checkout_proto_rawDesc = "" +
	"\n" +
	"\x0echeckout.proto\x12\ashop.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x05\n" +
	"\x11PlaceOrderRequest\x121\n" +
	"\x0ecustomer_email\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02`\x01R\rcustomerEmail\x12.\n" +
	"\rcustomer_name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x18<R\fcustomerName\x121\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0eidempotencyKey\x12:\n" +
	"\n" +
	"promo_note\x18\x04 \x01(\tB\x1b\xbaH\x18r\x162\x14^[A-Za-z0-9 ]{0,64}$R\tpromoNote\x129\n" +
	"\bcurrency\x18\x05 \x01(\x0e2\x11.shop.v1.CurrencyB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\bcurrency\x123\n" +
	"\x05items\x18\x06 \x03(\v2\x11.shop.v1.LineItemB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x102R\x05items\x124\n" +
	"\x10discount_percent\x18\a \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x00R\x0fdiscountPercent\x12-\n" +
	"\vcoupon_code\x18\b \x01(\tB\a\xbaH\x04r\x02\x18\x14H\x00R\n" +
	"couponCode\x88\x01\x01\x12G\n" +
	"\x0eshipping_speed\x18\t \x01(\x0e2\x16.shop.v1.ShippingSpeedB\b\xbaH\x05\x82\x01\x02\x10\x01R\rshippingSpeed\x12C\n" +
	"\x10shipping_address\x18\n" +
	" \x01(\v2\x10.shop.v1.AddressB\x06\xbaH\x03\xc8\x01\x01R\x0fshippingAddress\x12*\n" +
	"\faccept_terms\x18\v \x01(\bB\a\xbaH\x04j\x02\b\x01R\vacceptTerms\x12I\n" +
	"\x12requested_delivery\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x11requestedDelivery\x12+\n" +
	"\rpayment_token\x18\r \x01(\tB\x06\xe0A\x04\xe0A\x02R\fpaymentTokenB\x0e\n" +
	"\f_coupon_code\"\x87\x01\n" +
	"\bLineItem\x12'\n" +
	"\x03sku\x18\x01 \x01(\tB\x15\xbaH\x12r\x10\x10\x012\f^[A-Z0-9-]+$R\x03sku\x12#\n" +
	"\bquantity\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\bquantity\x12-\n" +
	"\n" +
	"unit_price\x18\x03 \x01(\x01B\x0e\xbaH\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\tunitPrice\"\x95\x01\n" +
	"\aAddress\x12\x1d\n" +
	"\x05line1\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05line1\x12\x1b\n" +
	"\x04city\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04city\x12\"\n" +
	"\acountry\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x02R\acountry\x12*\n" +
	"\vpostal_code\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18\n" +
	"R\n" +
	"postalCode\"c\n" +
	"\x12PlaceOrderResponse\x12\x1e\n" +
	"\border_id\x18\x01 \x01(\tB\x03\xe0A\x03R\aorderId\x12-\n" +
	"\bcurrency\x18\x02 \x01(\x0e2\x11.shop.v1.CurrencyR\bcurrency*?\n" +
	"\bCurrency\x12\x18\n" +
	"\x14CURRENCY_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03USD\x10\x01\x12\a\n" +
	"\x03EUR\x10\x02\x12\a\n" +
	"\x03GBP\x10\x03*J\n" +
	"\rShippingSpeed\x12\x1e\n" +
	"\x1aSHIPPING_SPEED_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSTANDARD\x10\x01\x12\v\n" +
	"\aEXPRESS\x10\x022h\n" +
	"\bCheckout\x12\\\n" +
	"\n" +
	"PlaceOrder\x12\x1a.shop.v1.PlaceOrderRequest\x1a\x1b.shop.v1.PlaceOrderResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/ordersB.Z,github.com/dvislobokov/protogen/genshop;shopb\x06proto3"

var (
	file_checkout_proto_rawDescOnce sync.Once
	file_checkout_proto_rawDescData []byte
)

func file_checkout_proto_rawDescGZIP() []byte {
	file_checkout_proto_rawDescOnce.Do(func() {
		file_checkout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checkout_proto_rawDesc), len(file_checkout_proto_rawDesc)))
	})
	return file_checkout_proto_rawDescData
}

var file_checkout_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_checkout_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_checkout_proto_goTypes = []any{
	(Currency)(0),                 // 0: shop.v1.Currency
	(ShippingSpeed)(0),            // 1: shop.v1.ShippingSpeed
	(*PlaceOrderRequest)(nil),     // 2: shop.v1.PlaceOrderRequest
	(*LineItem)(nil),              // 3: shop.v1.LineItem
	(*Address)(nil),               // 4: shop.v1.Address
	(*PlaceOrderResponse)(nil),    // 5: shop.v1.PlaceOrderResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_checkout_proto_depIdxs = []int32{
	0, // 0: shop.v1.PlaceOrderRequest.currency:type_name -> shop.v1.Currency
	3, // 1: shop.v1.PlaceOrderRequest.items:type_name -> shop.v1.LineItem
	1, // 2: shop.v1.PlaceOrderRequest.shipping_speed:type_name -> shop.v1.ShippingSpeed
	4, // 3: shop.v1.PlaceOrderRequest.shipping_address:type_name -> shop.v1.Address
	6, // 4: shop.v1.PlaceOrderRequest.requested_delivery:type_name -> google.protobuf.Timestamp
	0, // 5: shop.v1.PlaceOrderResponse.currency:type_name -> shop.v1.Currency
	2, // 6: shop.v1.Checkout.PlaceOrder:input_type -> shop.v1.PlaceOrderRequest
	5, // 7: shop.v1.Checkout.PlaceOrder:output_type -> shop.v1.PlaceOrderResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_checkout_proto_init() }
func file_checkout_proto_init() {
	if File_checkout_proto != nil {
		return
	}
	file_checkout_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checkout_proto_rawDesc), len(file_checkout_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checkout_proto_goTypes,
		DependencyIndexes: file_checkout_proto_depIdxs,
		EnumInfos:         file_checkout_proto_enumTypes,
		MessageInfos:      file_checkout_proto_msgTypes,
	}.Build()
	File_checkout_proto = out.File
	file_checkout_proto_goTypes = nil
	file_checkout_proto_depIdxs = nil
}
