// Code generated by protogenall. DO NOT EDIT.
// source: checkout.proto
//
// Reverse proxy: translates RESTful JSON into gRPC.

package shop

import (
	context "context"
	errors "errors"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	grpclog "google.golang.org/grpc/grpclog"
	metadata "google.golang.org/grpc/metadata"
	status "google.golang.org/grpc/status"
	proto "google.golang.org/protobuf/proto"
	io "io"
	http "net/http"
)

func request_Checkout_PlaceOrder_0(ctx context.Context, marshaler runtime.Marshaler, client CheckoutClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq PlaceOrderRequest
	var metadata runtime.ServerMetadata
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.PlaceOrder(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_Checkout_PlaceOrder_0(ctx context.Context, marshaler runtime.Marshaler, server CheckoutServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq PlaceOrderRequest
	var metadata runtime.ServerMetadata
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.PlaceOrder(ctx, &protoReq)
	return msg, metadata, err
}

// RegisterCheckoutHandlerServer registers the http handlers for service Checkout to "mux",
// calling CheckoutServer directly (in-process, no network round trip).
func RegisterCheckoutHandlerServer(ctx context.Context, mux *runtime.ServeMux, server CheckoutServer) error {
	mux.Handle(http.MethodPost, pattern_Checkout_PlaceOrder_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/shop.v1.Checkout/PlaceOrder", runtime.WithHTTPPathPattern("/v1/orders"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_Checkout_PlaceOrder_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_Checkout_PlaceOrder_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	return nil
}

// RegisterCheckoutHandlerFromEndpoint dials "endpoint" and registers the handlers.
func RegisterCheckoutHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()
	return RegisterCheckoutHandler(ctx, mux, conn)
}

// RegisterCheckoutHandler registers the http handlers, forwarding over "conn".
func RegisterCheckoutHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterCheckoutHandlerClient(ctx, mux, NewCheckoutClient(conn))
}

// RegisterCheckoutHandlerClient registers the http handlers for service Checkout,
// forwarding requests to the gRPC endpoint over the given CheckoutClient.
func RegisterCheckoutHandlerClient(ctx context.Context, mux *runtime.ServeMux, client CheckoutClient) error {
	mux.Handle(http.MethodPost, pattern_Checkout_PlaceOrder_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/shop.v1.Checkout/PlaceOrder", runtime.WithHTTPPathPattern("/v1/orders"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_Checkout_PlaceOrder_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_Checkout_PlaceOrder_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	return nil
}

var (
	pattern_Checkout_PlaceOrder_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"v1", "orders"}, ""))
)

var (
	forward_Checkout_PlaceOrder_0 = runtime.ForwardResponseMessage
)
